.\"
.\"  Write 1.0.0
.\"  Copyright (C) 1997  Jamie Howard <howardjp@dragon.ham.muohio.edu>
.\"
.\"  This program is free software; you can redistribute it and/or modify
.\"  it under the terms of the GNU General Public License as published by
.\"  the Free Software Foundation; either version 2 of the License, or
.\"  (at your option) any later version.
.\"
.\"  This program is distributed in the hope that it will be useful,
.\"  but WITHOUT ANY WARRANTY; without even the implied warranty of
.\"  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\"  GNU General Public License for more details.
.\"
.\"  You should have received a copy of the GNU General Public License
.\"  along with this program; if not, write to the Free Software
.\"  Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
.\"
.TH WRITE 1 "October 15, 1997" "Write" "Linux User's Manual"
.SH NAME
write \- send a message to another user
.SH SYNOPSIS
.B write
.I user<@host><#tty> <tty>
.SH DESCRIPTION
.B Write
permites you to communicte with other users by transfering lines from your
terminal to thiers.  
.B Write 
opens the receiving user's tty and sends a message in the format:
.PP
.RS
.PD 0
.TP
Message from user@host on tty at hh:mm...
.PD
.RE
.PP
At this point, the caller's lines will be copied to the receiving user's
tty.  
.B Write 
will continue tranfering lines of text until and end-of-file marker is
encountered or the program is terminated.  When terminated, 
.B write 
sends the line "EOF (user@host)" to the receiving user's terminal then
closes the connection.
.PP
The usual protocol for users communicating via 
.B write 
is to end lines with "-o" to signal the other user that it is time to
talk.  The text "oo" is used to indicated the conversation is believed to
be over.
.PP
If a line begins with "!", 
.B write
interprets the following text as a command line and passes it to 
.BR sh (1).
.PP
.B Write 
permission can be denied using 
.BR mesg (1).
.PP
.B mesg 
displays the current settings.
.SH FILES
.PD 0
.TP
.I /bin/sh
.TP
.I /dev/tty* 
.TP
.I /var/run/utmp
.PD
.SH SEE ALSO
.BR finger (1),
.BR mesg (1), 
.BR talk (1), 
.BR wall (1), 
.BR write (7),
.BR writed (8)
.SH HISTORY
.B Write
appeared in Sixth Edition AT&T UNIX.  The network aware
.B write
was developed at the Massachusetts Institute of Technology as part of 
Project Athena.
